# Generated by Django 4.2.30 on 2026-05-29 06:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("payment_pending", "Payment Pending"),
                            ("paid", "Paid"),
                            ("payment_failed", "Payment Failed"),
                            ("shipping", "Shipping"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("shipping_address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("created", "Created"),
                            ("payment_pending", "Payment Pending"),
                            ("paid", "Paid"),
                            ("payment_failed", "Payment Failed"),
                            ("shipping", "Shipping"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("payment_pending", "Payment Pending"),
                            ("paid", "Paid"),
                            ("payment_failed", "Payment Failed"),
                            ("shipping", "Shipping"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("product_name", models.CharField(max_length=255)),
                ("product_sku", models.CharField(max_length=100)),
                ("product_image_url", models.URLField(max_length=500)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.PositiveIntegerField()),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
                "ordering": ["id"],
            },
        ),
    ]
